#!/usr/bin/env python3
"""
Archpilot CLI v4.3
Commands:
  init    — scaffold .specs/ directory structure
  lint    — validate .specs/ against enterprise standards (tiers 1-3)
  run     — execute the full 5-stage agentic pipeline (requires ANTHROPIC_API_KEY)
  review  — re-run guardrail audit on existing .specs/ artifacts
  drift   — detect drift between LLD API specs and actual source code
  push    — push epics and stories from requirements.md to Jira or Azure DevOps
"""

import os
import sys
import re
import json
import argparse

__version__ = "4.3.0"


# ─── INIT ────────────────────────────────────────────────────────────────────

def init_project(target_dir: str) -> None:
    """Scaffold the Archpilot Spec-Kit directory structure."""
    specs_dir = os.path.join(target_dir, ".specs")
    if not os.path.exists(specs_dir):
        os.makedirs(specs_dir)

    files = {
        "Input.md": (
            "# High-Level Requirement Input\n\n"
            "> Paste your business requirement here. Be specific about the domain,\n"
            "> the business problem, key personas, and any known constraints.\n"
            "> Minimum 2-3 sentences. The richer the input, the deeper the discovery.\n\n"
            "## Requirement\n\n"
            "[Your requirement here]\n\n"
            "## Known Constraints\n\n"
            "- Budget: \n"
            "- Timeline: \n"
            "- Tech preferences: \n"
            "- Regulatory: \n"
        ),
        "constitution.md": (
            "# Project Constitution\n\n"
            "<!-- Hard constraints and boundaries for all AI agents in this pipeline. -->\n\n"
            "## Tech Stack\n- \n\n"
            "## Hard Constraints\n- \n\n"
            "## Out of Scope\n- \n"
        ),
        "discovery.md":    "# Discovery\n\n<!-- Generated by Phase 0: SE Agent -->\n",
        "requirements.md": "# Requirements\n\n<!-- Generated by Phase 1: PO Agent -->\n",
        "Design_HLD.md":   "# High-Level Design\n\n<!-- Generated by Phase 2: Arch Agent -->\n",
        "assumptions.md":  "# Assumptions Log\n\n| ID | Assumption | Owner | Status |\n|----|-----------:|-------|--------|\n",
        "volumetrics.md":  "# Volumetrics\n\n| Metric | Nominal | Peak | Basis |\n|--------|--------:|-----:|-------|\n",
        "dependencies.md": "# External Dependencies\n\n| Name | Owner | Type | Risk |\n|------|-------|------|------|\n",
        "critical_path.md":"# Critical Path\n\n| Milestone | Dependency | Owner | Date |\n|-----------|------------|-------|------|\n",
        "tasks.md":        "# Implementation Tasks\n\n<!-- Generated by Phase 3: Arch Agent (LLDs) -->\n",
    }

    print("\nInitializing Archpilot project...")
    for filename, content in files.items():
        filepath = os.path.join(specs_dir, filename)
        if not os.path.exists(filepath):
            with open(filepath, "w", encoding="utf-8") as f:
                f.write(content)
            print(f"  [OK]   Created  {filepath}")
        else:
            print(f"  [SKIP] Exists   {filepath}")

    prog = os.path.basename(sys.argv[0])
    print(
        f"\n[OK] Project initialized at {specs_dir}\n"
        "  Next steps:\n"
        "  1. Edit .specs/Input.md        — add your high-level requirement\n"
        "  2. Edit .specs/constitution.md — set hard constraints and tech preferences\n"
        f"  3. Run: {prog} run\n"
    )


# ─── LINT ─────────────────────────────────────────────────────────────────────

WEAK_WORDS = [
    "fast", "scalable", "resilient", "efficient", "flexible",
    "highly-available", "performant", "robust", "seamless", "modern",
]

def _strip_code_blocks(text: str) -> str:
    """Remove fenced code blocks so lint rules don't fire on code samples."""
    return re.sub(r'```.*?```', '', text, flags=re.DOTALL)

def lint_specs(target_dir: str, tier: int = 2, fmt: str = "text") -> None:
    """Lint .specs/ for structural and quality violations."""
    specs_dir = os.path.join(target_dir, ".specs")
    if not os.path.exists(specs_dir):
        _lint_out(fmt, [], [], "lint", f"{specs_dir} does not exist. Run 'init' first.")
        sys.exit(1)

    error_list = []
    warn_list  = []

    def add_error(msg): error_list.append(msg)
    def add_warn(msg):  warn_list.append(msg)

    if fmt == "text":
        print(f"\nRunning Archpilot Linter (Tier {tier})...")
        print("-" * 50)

    # -- Rule 1: No TODOs, TBDs, placeholders ---------------------------------
    for filename in sorted(os.listdir(specs_dir)):
        if not filename.endswith(".md"):
            continue
        filepath = os.path.join(specs_dir, filename)
        with open(filepath, "r", encoding="utf-8") as f:
            raw = f.read()
        lines_raw = raw.splitlines()
        plain = _strip_code_blocks(raw)
        lines  = plain.splitlines()

        for i, line in enumerate(lines_raw, 1):
            if re.search(r'\b(TODO|TBD|FIXME)\b', line, re.IGNORECASE):
                add_error(f"{filename}:{i}  Unresolved: '{line.strip()}'")
            if re.search(r'\[Your .+? here\]|\[placeholder\]|\[TBD\]', line, re.IGNORECASE):
                add_error(f"{filename}:{i}  Unfilled placeholder: '{line.strip()}'")

        for i, line in enumerate(lines, 1):
            for word in WEAK_WORDS:
                if re.search(rf'\b{word}\b', line, re.IGNORECASE):
                    msg = f"{filename}:{i}  Vague adjective '{word}' — use a quantified NFR (Rule 00:1.5)."
                    if tier >= 2:
                        add_error(msg)
                    else:
                        add_warn(msg)

    # -- Rule 2: Discovery dimension count ------------------------------------
    discovery_file = os.path.join(specs_dir, "discovery.md")
    if os.path.exists(discovery_file):
        with open(discovery_file, encoding="utf-8") as f:
            content = f.read()
        dim_count = len(re.findall(
            r'^#{2,3}\s.*(?:Dimension|Physics|Regulatory|Compliance|Security|'
            r'Resilience|FinOps|Cost|Residency|Edge|Connectivity|Observability|'
            r'Lifecycle|Interface|Privacy|Third.Party|Scaling|Sustainability|'
            r'Interrogation|Trade.off)',
            content, re.MULTILINE | re.IGNORECASE
        ))
        if tier == 3 and dim_count < 10:
            add_error(f"discovery.md has {dim_count} dimensions — Tier 3 requires ≥10 (Rule 50).")
        elif dim_count < 5:
            add_warn(f"discovery.md has only {dim_count} dimensions — recommend ≥10.")
    else:
        if tier >= 2:
            add_error("discovery.md missing — run 'archpilot run' to generate.")

    # -- Rule 3: Epic and Story counts ----------------------------------------
    req_file = os.path.join(specs_dir, "requirements.md")
    if os.path.exists(req_file):
        with open(req_file, encoding="utf-8") as f:
            content = f.read()
        epic_count  = len(re.findall(r'^#{2}\s+EP-\d+|^#{2}\s+Epic', content, re.MULTILINE))
        story_count = len(re.findall(r'^#{3,4}\s+.*S-\d+|^#{3,4}\s+(?:User Story|Story)', content, re.MULTILINE))

        if tier == 3:
            if epic_count < 10:
                add_error(f"requirements.md: {epic_count} Epics — Tier 3 requires 10-20 (Rule 50).")
            if story_count < 50:
                add_error(f"requirements.md: {story_count} Stories — Tier 3 requires 50-150 (Rule 50).")
        elif tier == 2 and epic_count < 5:
            add_warn(f"requirements.md: only {epic_count} Epics detected.")

    # -- Rule 4: HLD mandatory sections ---------------------------------------
    design_files = [
        f for f in os.listdir(specs_dir)
        if f.startswith("Design_") and f.endswith(".md")
    ]
    for filename in design_files:
        filepath = os.path.join(specs_dir, filename)
        with open(filepath, encoding="utf-8") as f:
            content = f.read()

        if "Design Rationale" not in content:
            add_error(f"{filename}: Missing 'Design Rationale' narrative (Rule 50).")
        if "Implementation Strategy" not in content:
            add_error(f"{filename}: Missing 'Implementation Strategy' narrative (Rule 50).")

        table_count = content.count("|---")
        if tier == 3 and table_count < 2:
            add_error(f"{filename}: Tier 3 requires ≥2 data/API tables.")

        if "```mermaid" not in content:
            add_warn(f"{filename}: No Mermaid diagram found — diagrams are strongly recommended.")

    # -- Rule 5: Governance artifact presence ---------------------------------
    for gf in ["assumptions.md", "volumetrics.md", "dependencies.md", "critical_path.md"]:
        if not os.path.exists(os.path.join(specs_dir, gf)):
            add_error(f"Missing governance artifact: {gf}")

    # -- Rule 6: Task verification (Tier 3) -----------------------------------
    task_file = os.path.join(specs_dir, "tasks.md")
    if os.path.exists(task_file):
        with open(task_file, encoding="utf-8") as f:
            content = f.read()
        if tier == 3 and "Verification" not in content and "Acceptance" not in content:
            add_error("tasks.md: Tier 3 requires explicit Verification/Acceptance criteria per task.")

    # -- Rule 7: NFR targets --------------------------------------------------
    for filename in design_files:
        filepath = os.path.join(specs_dir, filename)
        with open(filepath, encoding="utf-8") as f:
            content = f.read()
        nfr_section = re.search(r'Non.Functional.*?(?=\n#{1,3} |\Z)', content, re.DOTALL | re.IGNORECASE)
        if nfr_section:
            nfr_text = nfr_section.group()
            if not re.search(r'\d+\s*(?:ms|s|%|TPS|RPS|GB|TB|hrs?|days?)', nfr_text):
                add_warn(f"{filename}: NFR section lacks quantified targets (ms/s/%/TPS).")

    # -- Output ---------------------------------------------------------------
    _lint_out(fmt, error_list, warn_list, "text" if fmt == "text" else "json")

    if error_list:
        sys.exit(1)
    sys.exit(0)


def _lint_out(fmt: str, errors: list, warnings: list, mode: str, fatal: str = "") -> None:
    if fatal:
        if fmt == "json":
            print(json.dumps({"fatal": fatal, "errors": [], "warnings": []}))
        else:
            print(f"Error: {fatal}")
        return

    if fmt == "json":
        print(json.dumps({"errors": errors, "warnings": warnings}, indent=2))
        return

    for msg in errors:
        print(f"  [ERROR] {msg}")
    for msg in warnings:
        print(f"  [WARN]  {msg}")

    print("\n" + "-" * 50)
    if errors:
        print(f"  LINT FAILED  — {len(errors)} error(s), {len(warnings)} warning(s).")
        print("  Block PR from merging until all errors are resolved.")
    else:
        print(f"  LINT PASSED  — 0 errors, {len(warnings)} warning(s).")
        print("  Architecture specs meet Archpilot Enterprise Standards.")


# ─── RUN (agentic pipeline) ───────────────────────────────────────────────────

def run_pipeline_cmd(
    target_dir: str, model: str, from_phase: int,
    max_tokens: int, persona: str | None, dry_run: bool,
) -> None:
    """Execute the full 5-stage agentic pipeline."""
    _ensure_pipeline()
    from tools.pipeline import run_pipeline
    run_pipeline(
        target_dir, model,
        from_phase=from_phase, max_tokens=max_tokens,
        persona=persona, dry_run=dry_run,
    )


def drift_cmd(target_dir: str, src_dir: str | None, fmt: str) -> None:
    """Check for drift between LLD spec endpoints and source code."""
    tools_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "tools")
    if tools_dir not in sys.path:
        sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    from tools.drift_check import drift_check
    drift_check(target_dir, src_dir, fmt)


def push_cmd(target_dir: str, target: str, dry_run: bool, epics_only: bool) -> None:
    """Push requirements.md epics/stories to Jira or Azure DevOps."""
    _ensure_tools()
    from tools.push_tracker import push
    push(target_dir, target, dry_run, epics_only)


def _ensure_tools() -> None:
    root = os.path.dirname(os.path.abspath(__file__))
    if root not in sys.path:
        sys.path.insert(0, root)


def review_cmd(target_dir: str, model: str, max_tokens: int) -> None:
    """Re-run the guardrail review against existing .specs/ artifacts."""
    _ensure_pipeline()
    from tools.pipeline import run_review_only
    run_review_only(target_dir, model, max_tokens=max_tokens)


def _ensure_pipeline() -> None:
    """Ensure tools/ is on the import path and anthropic is installed."""
    tools_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "tools")
    if tools_dir not in sys.path:
        sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    try:
        import anthropic  # noqa: F401
    except ImportError:
        print("anthropic SDK not installed. Run: pip install -r requirements.txt")
        sys.exit(1)


# ─── CLI ──────────────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(
        prog="archpilot",
        description="Archpilot CLI v4.1 — Enterprise Architecture as Code",
    )
    parser.add_argument("--version", action="version", version=f"archpilot {__version__}")
    subparsers = parser.add_subparsers(dest="command", help="Available commands")

    # init
    p_init = subparsers.add_parser("init", help="Scaffold .specs/ directory structure")
    p_init.add_argument("--dir", default=".", help="Target directory (default: current)")

    # lint
    p_lint = subparsers.add_parser("lint", help="Lint .specs/ for standards violations")
    p_lint.add_argument("--dir",    default=".", help="Directory containing .specs/")
    p_lint.add_argument(
        "--tier", type=int, default=2, choices=[1, 2, 3],
        help="Compliance tier 1=Starter, 2=Standard, 3=Enterprise (default: 2)"
    )
    p_lint.add_argument(
        "--format", dest="fmt", default="text", choices=["text", "json"],
        help="Output format: text (default) or json for CI tooling"
    )

    # run
    p_run = subparsers.add_parser(
        "run",
        help="Run the full 5-stage agentic pipeline (requires ANTHROPIC_API_KEY)"
    )
    p_run.add_argument("--dir",   default=".", help="Directory containing .specs/Input.md")
    p_run.add_argument(
        "--model", default="claude-sonnet-4-6",
        help="Claude model ID (default: claude-sonnet-4-6)"
    )
    p_run.add_argument(
        "--from-phase", type=int, default=0, choices=[0, 1, 2, 3, 4],
        metavar="N",
        help="Resume pipeline from phase N (0-4); reads existing artifacts for earlier phases"
    )
    p_run.add_argument(
        "--max-tokens", type=int, default=16000,
        help="Max output tokens per Claude call (default: 16000)"
    )
    p_run.add_argument(
        "--persona",
        choices=["enterprise-architect", "startup-cto", "security-architect",
                 "presales-solutioner", "vibe-code-reviewer"],
        default=None,
        help="Inject a persona into agent system prompts to tune their communication style"
    )
    p_run.add_argument(
        "--dry-run", action="store_true",
        help="Print what each phase would do without calling the Claude API"
    )

    # drift
    p_drift = subparsers.add_parser(
        "drift",
        help="Detect drift between LLD spec endpoints and source code"
    )
    p_drift.add_argument("--dir",    default=".", help="Project root directory (default: current)")
    p_drift.add_argument("--src",    default=None, help="Source code directory (auto-detected if omitted)")
    p_drift.add_argument(
        "--format", dest="fmt", default="text", choices=["text", "json"],
        help="Output format: text (default) or json"
    )

    # review
    p_review = subparsers.add_parser(
        "review",
        help="Re-run guardrail audit on existing .specs/ artifacts (requires ANTHROPIC_API_KEY)"
    )
    p_review.add_argument("--dir",   default=".", help="Directory containing .specs/")
    p_review.add_argument(
        "--model", default="claude-sonnet-4-6",
        help="Claude model ID (default: claude-sonnet-4-6)"
    )
    p_review.add_argument(
        "--max-tokens", type=int, default=16000,
        help="Max output tokens per Claude call (default: 16000)"
    )

    # push
    p_push = subparsers.add_parser(
        "push",
        help="Push epics and stories from requirements.md to Jira or Azure DevOps",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        description=(
            "Push generated requirements to your issue tracker.\n\n"
            "Jira env vars : JIRA_URL  JIRA_EMAIL  JIRA_API_TOKEN  JIRA_PROJECT_KEY\n"
            "ADO env vars  : ADO_ORG   ADO_PROJECT  ADO_PAT\n\n"
            "A .specs/push_manifest.json file tracks pushed IDs — re-running is safe."
        ),
    )
    p_push.add_argument(
        "--target", required=True, choices=["jira", "ado"],
        help="Issue tracker to push to: jira or ado (Azure DevOps)"
    )
    p_push.add_argument("--dir", default=".", help="Project root directory (default: current)")
    p_push.add_argument(
        "--dry-run", action="store_true",
        help="Preview what would be created without making any API calls"
    )
    p_push.add_argument(
        "--epics-only", action="store_true",
        help="Create Epics only — skip User Stories (useful for initial setup)"
    )

    args = parser.parse_args()

    if args.command == "init":
        init_project(args.dir)
    elif args.command == "lint":
        lint_specs(args.dir, args.tier, args.fmt)
    elif args.command == "run":
        run_pipeline_cmd(
            args.dir, args.model, args.from_phase, args.max_tokens,
            getattr(args, "persona", None), getattr(args, "dry_run", False),
        )
    elif args.command == "review":
        review_cmd(args.dir, args.model, args.max_tokens)
    elif args.command == "drift":
        drift_cmd(args.dir, args.src, args.fmt)
    elif args.command == "push":
        push_cmd(args.dir, args.target, args.dry_run, args.epics_only)
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
