#!/usr/bin/env python3
"""
Archpilot CLI v4.0
Commands:
  init    — scaffold .specs/ directory structure
  lint    — validate .specs/ against enterprise standards (tiers 1-3)
  run     — execute the full 5-stage agentic pipeline (requires ANTHROPIC_API_KEY)
  review  — re-run guardrail audit on existing .specs/ artifacts
"""

import os
import sys
import re
import argparse


# ─── INIT ────────────────────────────────────────────────────────────────────

def init_project(target_dir: str) -> None:
    """Scaffold the Archpilot Spec-Kit directory structure."""
    specs_dir = os.path.join(target_dir, ".specs")
    if not os.path.exists(specs_dir):
        os.makedirs(specs_dir)

    files = {
        "Input.md": (
            "# High-Level Requirement Input\n\n"
            "> Paste your business requirement here. Be specific about the domain,\n"
            "> the business problem, key personas, and any known constraints.\n"
            "> Minimum 2-3 sentences. The richer the input, the deeper the discovery.\n\n"
            "## Requirement\n\n"
            "[Your requirement here]\n\n"
            "## Known Constraints\n\n"
            "- Budget: \n"
            "- Timeline: \n"
            "- Tech preferences: \n"
            "- Regulatory: \n"
        ),
        "constitution.md": (
            "# Project Constitution\n\n"
            "<!-- Hard constraints and boundaries for all AI agents in this pipeline. -->\n\n"
            "## Tech Stack\n- \n\n"
            "## Hard Constraints\n- \n\n"
            "## Out of Scope\n- \n"
        ),
        "discovery.md":    "# Discovery\n\n<!-- Generated by Phase 0: SE Agent -->\n",
        "requirements.md": "# Requirements\n\n<!-- Generated by Phase 1: PO Agent -->\n",
        "Design_HLD.md":   "# High-Level Design\n\n<!-- Generated by Phase 2: Arch Agent -->\n",
        "assumptions.md":  "# Assumptions Log\n\n| ID | Assumption | Owner | Status |\n|----|-----------:|-------|--------|\n",
        "volumetrics.md":  "# Volumetrics\n\n| Metric | Nominal | Peak | Basis |\n|--------|--------:|-----:|-------|\n",
        "dependencies.md": "# External Dependencies\n\n| Name | Owner | Type | Risk |\n|------|-------|------|------|\n",
        "critical_path.md":"# Critical Path\n\n| Milestone | Dependency | Owner | Date |\n|-----------|------------|-------|------|\n",
        "tasks.md":        "# Implementation Tasks\n\n<!-- Generated by Phase 3: Arch Agent (LLDs) -->\n",
    }

    print("\nInitializing Archpilot project...")
    for filename, content in files.items():
        filepath = os.path.join(specs_dir, filename)
        if not os.path.exists(filepath):
            with open(filepath, "w", encoding="utf-8") as f:
                f.write(content)
            print(f"  [OK]   Created  {filepath}")
        else:
            print(f"  [SKIP] Exists   {filepath}")

    print(
        f"\n[OK] Project initialized at {specs_dir}\n"
        "  Next steps:\n"
        "  1. Edit .specs/Input.md  -- add your high-level requirement\n"
        "  2. Edit .specs/constitution.md -- set hard constraints and tech preferences\n"
        "  3. Run: python archpilot.py run\n"
    )


# ─── LINT ─────────────────────────────────────────────────────────────────────

WEAK_WORDS = [
    "fast", "scalable", "resilient", "efficient", "flexible",
    "highly-available", "performant", "robust", "seamless", "modern",
]

def lint_specs(target_dir: str, tier: int = 2) -> None:
    """Lint .specs/ for structural and quality violations."""
    specs_dir = os.path.join(target_dir, ".specs")
    if not os.path.exists(specs_dir):
        print(f"Error: {specs_dir} does not exist. Run 'init' first.")
        sys.exit(1)

    errors   = 0
    warnings = 0

    print(f"\nRunning Archpilot Linter (Tier {tier})...")
    print("-" * 50)

    # -- Rule 1: No TODOs, TBDs, placeholders -----------------------------
    for filename in sorted(os.listdir(specs_dir)):
        if not filename.endswith(".md"):
            continue
        filepath = os.path.join(specs_dir, filename)
        with open(filepath, "r", encoding="utf-8") as f:
            lines = f.readlines()

        for i, line in enumerate(lines, 1):
            if re.search(r'\b(TODO|TBD|FIXME)\b', line, re.IGNORECASE):
                print(f"  [ERROR] {filename}:{i}  Unresolved: '{line.strip()}'")
                errors += 1

            if re.search(r'\[Your .+? here\]|\[placeholder\]|\[TBD\]', line, re.IGNORECASE):
                print(f"  [ERROR] {filename}:{i}  Unfilled placeholder: '{line.strip()}'")
                errors += 1

            for word in WEAK_WORDS:
                if re.search(rf'\b{word}\b', line, re.IGNORECASE):
                    print(f"  [ERROR] {filename}:{i}  Vague adjective '{word}' — use a quantified NFR (Rule 00:1.5).")
                    errors += 1

    # -- Rule 2: Discovery dimension count (Tier 3: >=10) ------------------
    discovery_file = os.path.join(specs_dir, "discovery.md")
    if os.path.exists(discovery_file):
        with open(discovery_file, encoding="utf-8") as f:
            content = f.read()
        dim_count = len(re.findall(
            r'^#{2,3}\s.*(?:Dimension|Physics|Regulatory|Compliance|Security|'
            r'Resilience|FinOps|Cost|Residency|Edge|Connectivity|Observability|'
            r'Lifecycle|Interface|Privacy|Third.Party|Scaling|Sustainability|'
            r'Interrogation|Trade.off)',
            content, re.MULTILINE | re.IGNORECASE
        ))
        if tier == 3 and dim_count < 10:
            print(f"  [ERROR] discovery.md has {dim_count} dimensions — Tier 3 requires ≥10 (Rule 50).")
            errors += 1
        elif tier == 2 and dim_count < 5:
            print(f"  [WARN]  discovery.md has only {dim_count} dimensions — recommend ≥10.")
            warnings += 1
    else:
        if tier >= 2:
            print("  [ERROR] discovery.md missing — run 'archpilot run' to generate.")
            errors += 1

    # -- Rule 3: Epic and Story counts ------------------------------------
    req_file = os.path.join(specs_dir, "requirements.md")
    if os.path.exists(req_file):
        with open(req_file, encoding="utf-8") as f:
            content = f.read()
        epic_count  = len(re.findall(r'^#{2}\s+EP-\d+|^#{2}\s+Epic', content, re.MULTILINE))
        story_count = len(re.findall(r'^#{3,4}\s+.*S-\d+|^#{3,4}\s+(?:User Story|Story)', content, re.MULTILINE))

        if tier == 3:
            if epic_count < 10:
                print(f"  [ERROR] requirements.md: {epic_count} Epics — Tier 3 requires 10-20 (Rule 50).")
                errors += 1
            if story_count < 50:
                print(f"  [ERROR] requirements.md: {story_count} Stories — Tier 3 requires 50-150 (Rule 50).")
                errors += 1
        elif tier == 2:
            if epic_count < 5:
                print(f"  [WARN]  requirements.md: only {epic_count} Epics detected.")
                warnings += 1

    # -- Rule 4: HLD mandatory sections -----------------------------------
    design_files = [
        f for f in os.listdir(specs_dir)
        if f.startswith("Design_") and f.endswith(".md")
    ]
    for filename in design_files:
        filepath = os.path.join(specs_dir, filename)
        with open(filepath, encoding="utf-8") as f:
            content = f.read()

        if "Design Rationale" not in content:
            print(f"  [ERROR] {filename}: Missing 'Design Rationale' narrative (Rule 50).")
            errors += 1
        if "Implementation Strategy" not in content:
            print(f"  [ERROR] {filename}: Missing 'Implementation Strategy' narrative (Rule 50).")
            errors += 1

        table_count = content.count("|---")
        if tier == 3 and table_count < 2:
            print(f"  [ERROR] {filename}: Tier 3 requires ≥2 data/API tables.")
            errors += 1

        if "```mermaid" not in content:
            print(f"  [WARN]  {filename}: No Mermaid diagram found — diagrams are strongly recommended.")
            warnings += 1

    # -- Rule 5: Governance artifact presence -----------------------------
    gov_files = ["assumptions.md", "volumetrics.md", "dependencies.md", "critical_path.md"]
    for gf in gov_files:
        if not os.path.exists(os.path.join(specs_dir, gf)):
            print(f"  [ERROR] Missing governance artifact: {gf}")
            errors += 1

    # ── Rule 6: Task verification (Tier 3) ───────────────────────────────
    task_file = os.path.join(specs_dir, "tasks.md")
    if os.path.exists(task_file):
        with open(task_file, encoding="utf-8") as f:
            content = f.read()
        if tier == 3 and "Verification" not in content and "Acceptance" not in content:
            print("  [ERROR] tasks.md: Tier 3 requires explicit Verification/Acceptance criteria per task.")
            errors += 1

    # ── Rule 7: NFR targets ───────────────────────────────────────────────
    for filename in design_files:
        filepath = os.path.join(specs_dir, filename)
        with open(filepath, encoding="utf-8") as f:
            content = f.read()
        nfr_section = re.search(r'Non.Functional.*?(?=\n#{1,3} |\Z)', content, re.DOTALL | re.IGNORECASE)
        if nfr_section:
            nfr_text = nfr_section.group()
            has_numbers = bool(re.search(r'\d+\s*(?:ms|s|%|TPS|RPS|GB|TB|hrs?|days?)', nfr_text))
            if not has_numbers:
                print(f"  [WARN]  {filename}: NFR section lacks quantified targets (ms/s/%/TPS).")
                warnings += 1

    # -- Summary ----------------------------------------------------------
    print("\n" + "-" * 50)
    if errors > 0:
        print(f"  LINT FAILED  — {errors} error(s), {warnings} warning(s).")
        print("  Block PR from merging until all errors are resolved.")
        sys.exit(1)
    else:
        print(f"  LINT PASSED  — 0 errors, {warnings} warning(s).")
        print("  Architecture specs meet Archpilot Enterprise Standards.")
        sys.exit(0)


# ─── RUN (agentic pipeline) ───────────────────────────────────────────────────

def run_pipeline_cmd(target_dir: str, model: str) -> None:
    """Execute the full 5-stage agentic pipeline."""
    _ensure_pipeline()
    from tools.pipeline import run_pipeline
    run_pipeline(target_dir, model)


def review_cmd(target_dir: str, model: str) -> None:
    """Re-run the guardrail review against existing .specs/ artifacts."""
    _ensure_pipeline()
    from tools.pipeline import run_review_only
    run_review_only(target_dir, model)


def _ensure_pipeline() -> None:
    """Ensure tools/ is on the import path and anthropic is installed."""
    tools_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "tools")
    if tools_dir not in sys.path:
        sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    try:
        import anthropic  # noqa: F401
    except ImportError:
        print("anthropic SDK not installed. Run: pip install -r requirements.txt")
        sys.exit(1)


# ─── CLI ──────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        prog="archpilot",
        description="Archpilot CLI v4.0 — Enterprise Architecture as Code",
    )
    subparsers = parser.add_subparsers(dest="command", help="Available commands")

    # init
    p_init = subparsers.add_parser("init", help="Scaffold .specs/ directory structure")
    p_init.add_argument("--dir", default=".", help="Target directory (default: current)")

    # lint
    p_lint = subparsers.add_parser("lint", help="Lint .specs/ for standards violations")
    p_lint.add_argument("--dir",  default=".", help="Directory containing .specs/")
    p_lint.add_argument(
        "--tier", type=int, default=2, choices=[1, 2, 3],
        help="Compliance tier 1=Starter, 2=Standard, 3=Enterprise (default: 2)"
    )

    # run
    p_run = subparsers.add_parser(
        "run",
        help="Run the full 5-stage agentic pipeline (requires ANTHROPIC_API_KEY)"
    )
    p_run.add_argument("--dir",   default=".", help="Directory containing .specs/Input.md")
    p_run.add_argument(
        "--model", default="claude-sonnet-4-6",
        help="Claude model ID (default: claude-sonnet-4-6)"
    )

    # review
    p_review = subparsers.add_parser(
        "review",
        help="Re-run guardrail audit on existing .specs/ artifacts (requires ANTHROPIC_API_KEY)"
    )
    p_review.add_argument("--dir",   default=".", help="Directory containing .specs/")
    p_review.add_argument(
        "--model", default="claude-sonnet-4-6",
        help="Claude model ID (default: claude-sonnet-4-6)"
    )

    args = parser.parse_args()

    if args.command == "init":
        init_project(args.dir)
    elif args.command == "lint":
        lint_specs(args.dir, args.tier)
    elif args.command == "run":
        run_pipeline_cmd(args.dir, args.model)
    elif args.command == "review":
        review_cmd(args.dir, args.model)
    else:
        parser.print_help()
